### ISSUE TITLE
How can I have a dynamic verticalAlign?

### ISSUE THREAD

**Issue by diegohaz** [PolymerElements/paper-dropdown-menu#110] opened 2016-01-08 22:29 UTC
Based on the `paper-dropdown-menu` position on the screen? I still can't figure it out.

**Comment by cdata** [comment] 2016-01-29 23:04
This is an unimplemented feature. We should definitely do it. I think we already have an issue open (https://github.com/PolymerElements/paper-dropdown-menu/issues/85). I'm going to close this as a dupe of that issue.

**Closed by cdata** 2016-01-29 23:04 UTC
