### ISSUE TITLE
opening/closing menu makes page wobble

### ISSUE THREAD

**Issue by bipin-nag** [PolymerElements/paper-dropdown-menu#123] opened 2016-02-02 20:19 UTC
Page wobbles left and right when opening/closing menu. Can we not have this behaviour. It makes your site look cheap and buggy.

Demo page link showing same: https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html&active=paper-dropdown-menu

**Comment by okelepko** [comment] 2016-02-03 23:06
Moreover, if you click the select twice (once to open the menu, and another time while it's open), say good-bye to your scrollbar - you'll never see it again.

**Comment by bipin-nag** [comment] 2016-02-03 23:30
You are right, didnt see that. Some element/thing is making overflow hidden for body. After I do what you say there is a permanent overflow :hidden property on the body.

Now if I manually turn off overflow property from elements view (F12) after doing the above, open/close works without jiggle and the scroll bar shows but scrolling doesnt work anymore.

**Comment by okelepko** [comment] 2016-02-03 23:30
Ok, the click-twice thing seems to have been fixed: https://github.com/PolymerElements/iron-dropdown/issues/47

**Comment by cdata** [comment] 2016-02-04 20:03
Hi, thanks for reporting. This is a dupe of https://github.com/PolymerElements/iron-dropdown/issues/54, so I am going to close it. Please track https://github.com/PolymerElements/iron-dropdown/issues/54 for updates!

**Closed by cdata** 2016-02-04 20:03 UTC
