### ISSUE TITLE
Browser scrollbars blocked on paper-dropdown-menu

### ISSUE THREAD

**Issue by beppino** [PolymerElements/paper-dropdown-menu#119] opened 2016-01-28 14:05 UTC
Hello,
I've an urgent question for you: one of my customer, since 2/3 months ago, often say me that the application stop working when he works on a dialog with form.
This error was impossible to reproduce, so I'm very desperate...!
Since today, when I casually found the reproducing steps, confirmed when I've found the same error on the demo page in the polymer site.
This is: in a scrolling page (like https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html&active=paper-dropdown-menu) select a paper-dropdown-menu (in the demo page, better is to select that after 'No underline (menu from bottom)'). After, reselect the same paper-dropdown-menu (the menu close and reopen). Then select one other field. The browser scrolling doesn't works now! This for Chrome, Safari and Firefox but I suppose it's an all browser problem.
For hint, I've notated that when the dropdown open, in the body tag the style 'overflow: hidden;' it's added and removed if the dropdown close. When you reselect the same dropdown (menu close  and reopen) the style remain in the body tag and this block the browser scrolling.
I hope that my message can help you to resolve this issue, very important for me and, specially, for my client!
Thanks
-g

PS: Sorry for my bad english...

**Comment by cdata** [comment] 2016-01-29 23:34
Hi, thanks for reporting. I think this is a dupe of https://github.com/PolymerElements/paper-dropdown-menu/issues/109, so I'm going to close this one.

**Closed by cdata** 2016-01-29 23:34 UTC

**Comment by beppino** [comment] 2016-01-30 15:10
Thanks @cdata , and sorry. I had not seen the #109 report.
-g

**Comment by Dharshika9** [comment] 2019-06-15 17:23
I am facing the same issue that i couldn't scroll the main page when paper-dropdown-menu is opened.Its highly effecting on my mobile view of the page.@cdata
