### ISSUE TITLE
Disabled always

### ISSUE THREAD

**Issue by glaucomunsberg** [PolymerElements/paper-dropdown-menu#10] opened 2015-08-09 00:57 UTC
no matter what I do, disabled is always true, the demo have the same too 

![screenshot from 2015-08-08 21-55-16](https://cloud.githubusercontent.com/assets/1040010/9153052/6f412e0c-3e18-11e5-895c-99386a0d6e11.png)

**Comment by cdata** [comment] 2015-08-10 20:45
Hi, I cannot reproduce this. Can you provide more specific repro steps, a browser and / or a test case in JSBin or Code Pen?

**Comment by glaucomunsberg** [comment] 2015-08-14 14:01
Hi @cdata, So I'm using a long list of elements at my project in RoR, you can see this list at [my repo](https://github.com/glaucomunsberg/atHome/blob/version_2/app/app/assets/components/application.html.erb) , when I opened the demo inside the RoR application the same problem occurred. Someone take the same problem? Or some like that?

**Comment by glaucomunsberg** [comment] 2015-08-19 02:14
if I get the element document.querySelector('paper-dropdown-menu') and try to set the opened to true the error "Uncaught ReferenceError: KeyframeEffect is not defined" occured

**Comment by glaucomunsberg** [comment] 2015-08-19 02:36
updating my paper-dropdown-menu to 1.0.2 version and using the demo code
```
<paper-dropdown-menu label="Your favourite pastry">
  <paper-menu class="dropdown-content">
    <paper-item>Croissant</paper-item>
    <paper-item>Donut</paper-item>
    <paper-item>Financier</paper-item>
    <paper-item>Madeleine</paper-item>
  </paper-menu>
</paper-dropdown-menu>
```
I got this result, note that is desabled and the menu was opened by js manually.
![paper-dropdown-menu](https://cloud.githubusercontent.com/assets/1040010/9347537/521bbdf6-4601-11e5-8a94-241472bb3e61.png)

**Comment by dbruechner** [comment] 2015-08-20 15:40
same problem here

**Comment by glaucomunsberg** [comment] 2015-08-22 21:44
@dbruechner and @cdata I solved my problem temporary with this
```
$(document).ready(function(){
          paper_dropdowns = document.querySelectorAll('paper-dropdown-menu');
          for(a=0; a < paper_dropdowns.length;a++){
            paper_dropdowns[a].disabled = false;
            paper_dropdowns[a].querySelector('paper-input').disabled = false;
            paper_dropdowns[a].querySelector('paper-menu-button').disabled = false;
            paper_dropdowns[a].querySelector('iron-dropdown').disabled = false;
          }
        });
```

**Comment by dbruechner** [comment] 2015-08-24 13:57
Thanks @glaucomunsberg 

One additional thing to your solution, I'd wait for WebComponentsReady, just to be sure every polymer component has been loaded at that point.

```javascript
document.addEventListener('WebComponentsReady', function() {
 paper_dropdowns = document.querySelectorAll('paper-dropdown-menu');
  for(a=0; a < paper_dropdowns.length;a++){
    paper_dropdowns[a].disabled = false;
    paper_dropdowns[a].querySelector('paper-input').disabled = false;
    paper_dropdowns[a].querySelector('paper-menu-button').disabled = false;
    paper_dropdowns[a].querySelector('iron-dropdown').disabled = false;
  }

});
```

**Comment by glaucomunsberg** [comment] 2015-08-24 14:27
@dbruechner you're right! =D but note that this will enable all paper-dropdowns, some cases the disabled attribute is desired. So I solve this problem finding only the paper-dropdown that I wanted.

**Comment by cdata** [comment] 2016-01-28 20:36
Hi, since there is no reduced test case for this, I'm going to close the issue. Please re-open with a test case.

For more details, please refer to our [contributing guidelines](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/paper-dropdown-menu.html)!

**Closed by cdata** 2016-01-28 20:36 UTC

**Comment by glaucomunsberg** [comment] 2016-02-09 18:03
@dbruechner are you using the gem [polymer-rails](https://github.com/alchapone/polymer-rails) from @alchapone to your application on RoR? I guess  the issue is there 🤔

**Comment by JustLey** [comment] 2016-07-28 07:08
@glaucomunsberg I'm having the same issue. Not sure how often polymer-related gems are being updated, but sure have run on a lot of issues lately.

**Comment by glaucomunsberg** [comment] 2016-07-28 12:36
@JustLey Do you use polymer-rails?
