### ISSUE TITLE
Refresh of selected item

### ISSUE THREAD

**Issue by ulrichSchreiner** [PolymerElements/paper-dropdown-menu#23] opened 2015-08-18 15:11 UTC
hi,

i have a `paper-dropdown-menu` with a nested `paper-menu` with a list of `paper-item`'s.  The items are rendered with a `dom-repeat` from a list a data values. If i change the list of value's the `paper-menu` contains the new values, but the `paper-dropdown-menu` still contain's the old selected item, which is an illegal value now because the selected value of the dropdown is not contained in the new list.

It get's really ugly if the old and new list of `paper-item`'s contains only one element with different values. As the `selected` property of `paper-menu` does not change (it was 0 and it is 0 with the new list), no event is fired when i click the new value in the new list. --> i cannot select the single value from my new menu list. Well i can select it with `paper-menu`, but this value is not reflected in `papwer-dropdown-menu`.

it would be great to have the option to bind the selected-item explicitly

**Comment by kungufli** [comment] 2015-08-26 11:50
I have this exact same problem. I think the content of the `paper-input-container` should be updated automatically when the `paper-menu` content is generated from data-binding and the data structure changes.

**Comment by notthetup** [comment] 2015-08-28 13:53
Yup. I'm noticing this as well. Any known workarounds?

**Comment by zmoshansky** [comment] 2015-09-04 01:26
After my backing data changes, the following does the trick (In particular, `_setSelectedItem`):
```
 this.$$('paper-menu').select(0);
 this.$$('paper-dropdown-menu')._setSelectedItem(null);
 this.$$('paper-dropdown-menu')._setSelectedItem(this.$$('paper-menu').selectedItem);
 this._paper-dropdown-menu-on-iron-select-callback(); // Not fired automatically
```

I believe it's because paper-menu doesn't emit an iron-select after it's backing data changes

**Comment by kungufli** [comment] 2015-09-04 11:15
@zmoshansky how exactly do you execute the `_onIronSelect(event)` callback on the `paper-dropdown-menu`? Which event are you passing as parameter?

**Comment by zmoshansky** [comment] 2015-09-04 16:09
I'm not actually calling `paper-dropdown-menu`'s `_onIronSelect(event)`, to do that I would try something of the form `this.$$('paper-menu').fire('iron-select', this.$$('paper-menu').selectedItem);` (quick testing didn't work).

Thus the workaround, replicating the behaviour through:
```
<paper-dropdown-menu>
  ....
  <paper-menu on-iron-select="_superDuperHandler"></....>
</...>
```
```
this.$$('paper-menu').select(0);
this.$$('paper-dropdown-menu')._setSelectedItem(null);
this.$$('paper-dropdown-menu')._setSelectedItem(this.$$('paper-menu').selectedItem);
this._superDuperHandler(args);
```

**Comment by kungufli** [comment] 2015-09-07 14:28
Thank you @zmoshansky, this is very useful as workaround until someone fixes the problem on the `paper-dropdown-menu` itself.

**Comment by Gwalks91** [comment] 2015-09-14 21:45
+1

**Comment by notwaldorf** [comment] 2016-01-28 22:27
I think this should have been fixed with a PR in iron-selector. Please re-open if this is still reproducible.

**Closed by notwaldorf** 2016-01-28 22:27 UTC

**Comment by kungufli** [comment] 2016-02-05 10:20
@notwaldorf which PR in `iron-selector` is supposed to resolve this issue? I was thinking at https://github.com/PolymerElements/iron-selector/pull/100 but this is already merged and I still have the issue with the version 1.2.1 of `iron-selector`.

**Comment by zmoshansky** [comment] 2016-02-16 20:09
I can also confirm that this is still reproducible.

**Comment by kungufli** [comment] 2016-03-11 11:50
@ulrichSchreiner @notwaldorf can you re-open this please? The issue is still there. Thanks

**Comment by wc-matteo** [comment] 2016-09-16 10:56
This worked for me:

```js
// update data values used by dom-repeat here...

window.setTimeout(() => {
  this.$$('paper-listbox').selectIndex(-1)
  this.$$('paper-listbox').selectIndex(0)
}, 0)
```

When the values given to the repeater change, the dropdown-menu selected item is reset to the first.
