### ISSUE TITLE
Indicate that paper-menu is required

### ISSUE THREAD

**Issue by gjuchault** [PolymerElements/paper-dropdown-menu#24] opened 2015-08-20 17:52 UTC
Hi,

After a few tests, I managed to see that if paper-menu isn't included, there is no way to select any of the elements of the submenu. Shouldn't that be documented ?

**Comment by mrherndon** [comment] 2015-10-08 16:20
I ran into this same issue.  I thought the element was broken for a least an hour.

**Comment by morficus** [comment] 2015-11-01 20:48
+1 - I ran in to the same problem

**Comment by morficus** [comment] 2015-12-13 02:50
As of commit 50cbe8fa2553e8fef84fc76cbdc12221d4b34391, it appears that `paper-listbox` is now prefered over `paper-menu`

**Comment by notwaldorf** [comment] 2016-01-28 22:31
Closing as a duplicate of https://github.com/PolymerElements/paper-dropdown-menu/issues/97

**Closed by notwaldorf** 2016-01-28 22:31 UTC
