### ISSUE TITLE
paper-dropdown-menu doesn't close after tapping the selected item

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-dropdown-menu#163] opened 2016-06-12 14:13 UTC
Fiddle: https://jsfiddle.net/j4rfjasf/

Start with a `paper-dropdown-menu` with nothing selected, as in the fiddle.

Steps:

1. Click the `paper-dropdown-menu`; the menu/listbox opens.
2. Click an item; the menu/listbox closes.
3. Click the dropdown again; the menu/listbox opens.
4. Click the same item as in 2, which is now bold.

Expected: The menu closes.
Actual: Nothing happens.

Compare with native `<select>` behavior, which closes after tapping any item, even if that item is already selected.

**Comment by valdrinkoshi** [comment] 2016-06-29 22:47
This looks like a duplicate of https://github.com/PolymerElements/paper-dropdown-menu/issues/72

**Closed** 2016-06-29 22:50 UTC
Labels: source: hooli, started
