### ISSUE TITLE
adding :before selector to paper-dropdown-menu causes odd layout

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/paper-dropdown-menu#153] opened 2016-04-21 23:58 UTC
### Description

Adding a `:before` selector to the element seems to cause it to wrap down a line and nothing appears to fix this... the selector in question was this:
```
    span:before, paper-dropdown-menu:before {
      content: '»';
      color: #DD4B39;
      padding: 0 10px;
    }
```
### Expected outcome
I would expect this to just prefix the dropdown with the above content

### Actual outcome
Instead, the menu appears below the content as if it wrapped to a new line.

### Live Demo

Public demo N/A - will see if I can reproduce on JSBIN later (but I can provide an internal link to a Google demo that shows this, just ping me)

### Browsers Affected

- [x ] Chrome
- [ ] Firefox (maybe -- trying to test it proved painful)
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

Notes: applying `float: left` to the `:before` content will fix this, still seems odd that it is needed though.

**Comment by valdrinkoshi** [comment] 2016-06-29 22:27
The issue is caused by the internal `paper-menu-button` which has `display: block` (which can be changed with the mixin http://jsbin.com/fegoho/3/edit?html,output), and by the `<div role="button">` before it (https://github.com/PolymerElements/paper-dropdown-menu/blob/master/paper-dropdown-menu.html#L88), which should be fixed by making it `position: absolute`, or changing it to a `span`.

**Closed** 2016-07-09 00:05 UTC
Labels: bug, p1 - backlog, started
