### ISSUE TITLE
Stacking push lock

### ISSUE THREAD

**Issue by MeinAccount** [PolymerElements/paper-dropdown-menu#109] opened 2015-12-30 20:23 UTC
1. Visit the [demo](https://elements.polymer-project.org/elements/paper-dropdown-menu?active=paper-dropdown-menu&view=demo:demo/index.html).
2. Press on the **label** `Letters` of `No underline (menu from bottom)` **twice**.
3. The scrolling is now permanently locked.

Clicking on the label twice causes two scroll locks to be pushed on `Polymer.IronDropdownScrollManager`. Closing the dropdown only removes one of these and the scrolling remains disabled.

**Comment by WilliamSWoodruff** [comment] 2016-01-07 21:58
+1 on this!

**Comment by WilliamSWoodruff** [comment] 2016-01-07 22:29
I put this chunk in the shell of the project and it's a fix for now!
``` javascript
this.addEventListener('paper-dropdown-open', function(e) {
    var dropdown = e.srcElement.querySelector("#dropdown");
    if(Polymer.IronDropdownScrollManager.currentLockingElement == dropdown) {
        Polymer.IronDropdownScrollManager.removeScrollLock(dropdown);
    }
});
```

**Comment by cdata** [comment] 2016-01-29 23:06
Nice catch! This is totally a bug..

**Comment by cdata** [comment] 2016-01-29 23:49
I'm going to close this as a dupe of https://github.com/PolymerElements/iron-dropdown/issues/47, since `iron-dropdown` is where this issue needs to be fixed.

**Closed by cdata** 2016-01-29 23:49 UTC
Labels: help wanted, p0 - critical
