### ISSUE TITLE
Dropdown not closing after selecting

### ISSUE THREAD

**Issue by Iskalla** [PolymerElements/paper-dropdown-menu#5] opened 2015-08-07 07:43 UTC
I think this has to do with something wrong in my dependencies or something. The thing is when I select an item, it becomes selected but the dropdown won't close and an error "Uncaught TypeError: Cannot set property 'right' of undefined"
The same happens when running your demo from my project.

![ezgif com-crop](https://cloud.githubusercontent.com/assets/11649446/9131061/9641e5cc-3ce8-11e5-92ec-c4af2ea6acd1.gif)

Also, I'm seeing the same behavior as #3 , is that normal?

**Comment by cdata** [comment] 2015-08-07 17:59
Hey, thanks for reporting. Can you give me details about the browser you are using? Also, anything else that may be particular to your development environment.

**Comment by Iskalla** [comment] 2015-08-08 00:50
Hi! 
I'm using the latest version of chrome,  I don't think there's anything particular about it.. :(
Since it's friday night here and all this is on my workplace I can't give you detailed info about it until monday.
The first thing I thought could be wrong was maybe iron-dropdown or paper-menu not updated, but I did update both this morning, the same keeps happening.
Thanks for taking interest (and sorry if my english is not perfect... )

**Comment by cdata** [comment] 2015-08-10 20:49
No worries, thanks for the details. Sometimes `bower` doesn't update everything. I would recommend trying to delete your `bower_components` folder and installing it from scratch. In the mean time, I will try out the dropdown on Chrome / Windows and see if I can reproduce the issue.

**Comment by Iskalla** [comment] 2015-08-11 06:05
I actually updated everything by hand before posting my issue. Did it again, the same happens

**Comment by pette9** [comment] 2015-08-15 20:36
I have the same issue Chrome `Version 43.0.2357.125 (64-bit)` on linux. apart from the `Uncaught TypeError: Cannot set property 'right' of undefined` error, I also get, `Uncaught TypeError: Polymer.Gestures.findOriginalTarget is not a function`

**Comment by suryakiranjuthuka** [comment] 2015-08-25 17:31
I have the same exact issue, please fix it.

**Comment by skullerj** [comment] 2015-08-27 16:17
Try updating polymer dependency to 1.1.0 that worked for me.

"polymer": "Polymer/polymer#^1.1.0"

**Comment by Iskalla** [comment] 2015-08-28 10:39
That didn't work for me. It does the same and also messes up every paper-tooltip on my webpage...

**Comment by aceLren** [comment] 2015-09-21 22:37
Stepping through the code of iron-dropdown in _updateOverlayPosition there's a test on line 416:

    if (this._fitInfo) {

Which is true, b/c in my case at least _fitInfo is an object with:

    {margin:...,positionedBy...,sizedBy...}

and then it tries to set inlineStyle, which is undefined (at least in my case).  Not sure what it is about my setup that is causing that, it's set as expected in the demo.

**Comment by aceLren** [comment] 2015-09-21 22:48
Ok, for whatever reason bower didn't update iron-fit-behavior.  If it's at 1.0.0 inlineStyle isn't defined.  Cleaning my bower folder fixed this.

**Comment by kgaree** [comment] 2015-09-24 20:53
same error for me. Fixed by installing iron-fit-behavior...
bower install --save PolymerElements/iron-fit-behavior

**Comment by miztroh** [comment] 2015-10-21 22:12
@cdata Can you take another look at this?  I'm having this issue in every browser I've tested when selecting a value using the ``enter`` key.  It selects the value, closes the dropdown, then immediate reopens it.  The issue happens on the catalog demo page as well.

https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html&active=paper-dropdown-menu

**Comment by SergioGeeK7** [comment] 2015-12-07 22:40
Hello. I have the issue .polymer#1.2.0 
Chrome V : 46.0.2490.86 . even in the demo page happends.

**Comment by cdata** [comment] 2016-01-27 22:35
Hi, I believe that this issue has been resolved. Please re-open if it is still occurring!

**Closed by cdata** 2016-01-27 22:35 UTC
Labels: ready

**Comment by SergioGeeK7** [comment] 2016-01-27 22:41
Works for me now... (Y)

**Comment by Duder-onomy** [comment] 2016-02-13 01:39
I am currently experiencing this issue. The menu will not close when selecting an item. 
This does not work even when I paste the example from the polymer website into my app. 

I have run `bower update`. My bower.json looks like this:

```json
"dependencies": {
    "polymer": "Polymer/polymer#^1.2.0",
    "paper-input": "PolymerElements/paper-input#^1.1.5",
    "paper-dropdown-menu": "PolymerElements/paper-dropdown-menu#^1.1.3",
    "paper-item": "PolymerElements/paper-item#^1.1.3",
    "paper-menu": "PolymerElements/paper-menu#^1.2.2",
    "paper-listbox": "polymerelements/paper-listbox#^1.1.2"
  }
```

Any tips? / Things I should checkout or look for?

**Comment by Duder-onomy** [comment] 2016-02-17 02:03
@cdata I am experiencing this issue in a very vanilla polymer implementation.  Do you have any advice? 

If I paste the example from the polymer website into my app, it does not work. So I know it is an issue with my app. But I have done almost nothing to the app. If I could figure out how to get polymer into a jsfiddle I would paste it here. 

Some interesting points, the selected attribute of `paper-menu` is not selecting the item. If I attach a listener to the `paper-menu` it is not firing the 'iron-select' event. So maybe it is an issue with paper-menu?

Any help is very appreciated.

**Comment by Duder-onomy** [comment] 2016-02-17 18:30
If anyone gets here and is having this same problem. 

I had it too, and I solved it by double checking every bower dependency. In my case, bower installing the `paper-dropdown-menu` does not install the child elements you will need in order to make it work. You need to explicitly bower install every element you use.  

So, the example from the polymer website 
```html
<paper-dropdown-menu label="Your favourite pastry">
  <paper-menu class="dropdown-content">
    <paper-item>Croissant</paper-item>
    <paper-item>Donut</paper-item>
    <paper-item>Financier</paper-item>
    <paper-item>Madeleine</paper-item>
  </paper-menu>
</paper-dropdown-menu>
```

Gives you the following bower install script to use the element: 
`bower install --save PolymerElements/paper-dropdown-menu`

My assumption was that installing the `paper-dropdown-menu` would also install its dependencies. This is not exactly the case. It will install only the dependencies it needs to function. In the html example above there are three dependencies. The 'paper-dropdown-menu', the 'paper-menu' and the 'paper-item'.  This was not obvious to me. Hopefully helps anyone else out.

**Comment by javiercbk** [comment] 2016-07-14 14:13
I'm sorry but I'm getting the same error.

To test this I've cloned the [polymer-starter-kit](https://github.com/PolymerElements/polymer-starter-kit) and added this to "my-greeting.html"

```html
    <paper-dropdown-menu label="Your favourite pastry">
      <paper-listbox class="dropdown-content">
        <paper-item>Croissant</paper-item>
        <paper-item>Donut</paper-item>
        <paper-item>Financier</paper-item>
        <paper-item>Madeleine</paper-item>
      </paper-listbox>
    </paper-dropdown-menu>
  </template>
```

But when I click any item, it does nothing. No error, just nothing.

I'm testing in chrome Version 51.0.2704.103 (64-bit) in Mac OS X.

I've tried what @Duder-onomy pointed out but I had no luck either.

How to test:

```sh
git clone https://github.com/PolymerElements/polymer-starter-kit
cd polymer-starter-kit
npm install
bower install
```
Add the paper-dropdown-menu snippet to my "my-greeting.html"
```sh
gulp serve
```
This is what you'll see. If you click on any element it won't get selected nor it will close the dropdown.
![screen shot 2016-07-14 at 11 12 22 am](https://cloud.githubusercontent.com/assets/1448426/16842452/ed379966-49b3-11e6-92e1-e3ea799d7364.png)

Cheers.

**Comment by dray-sams** [comment] 2016-09-07 15:38
I did a ```bash   bower install --save polymerelements/paper-listbox ``` and then imported it into my file and it worked like a charm. So basically you just have to make sure you have all the bower components you used in your ```paper-dropdown-menu`` inside your bower-components folder and also imported.
